import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

// No next/font/google here deliberately — that fetches font files from
// Google's CDN at build time, an external network dependency this
// placeholder doesn't need. Task 13 can add a real type system (and
// decide then whether that's a self-hosted font or next/font).
export const metadata: Metadata = {
  title: "kurtar",
  description: "kurtar — gün sonu sürpriz paket pazaryeri",
};

// A plain `{ children: ReactNode }`, not Next 16's generated `LayoutProps<"/">`
// helper — that type only exists after `.next/types` has been generated by a
// prior build/dev run, which would make a clean checkout's very first
// `tsc --noEmit` fail before anything has ever been built.
export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="tr">
      <body>{children}</body>
    </html>
  );
}
